export const MINI_LEDGER_TURN_PROMPTS = Object.freeze([
  `Implement the candidate contract in this isolated workspace. Leave executable ledger.mjs; you may create supporting source files but may not use packages, network access, host files, or secrets. The persistent state is ledger.json with exact shape {"schemaVersion":"agentbattler.ledger.v1","events":[{"id":string,"kind":string,"payload":JSON,"sequence":integer}]}. CLI: node ledger.mjs append --id ID --kind KIND --payload JSON; node ledger.mjs get --id ID; node ledger.mjs query --kind KIND [--limit N]; node ledger.mjs export PATH; node ledger.mjs import PATH; node ledger.mjs recover. Commands emit JSON to stdout and non-zero exit on invalid input or missing required records. Ordering is deterministic by sequence, then ID. Turn 1: implement append and get; append a1/task {title:first}, a2/note {title:second}; get a1. Modify only candidate source files.`,
  `Preserve all prior behavior and modify only candidate source files. Turn 2: add deterministic kind filtering and limits. Append b1/task {title:third}; query task with limit 10 must return a1,b1 in order.`,
  `Preserve all prior behavior and modify only candidate source files. Turn 3: add export PATH. It writes the complete v1 state without changing the live ledger and reports exported:3.`,
  `Preserve all prior behavior and modify only candidate source files. Turn 4: add import PATH into a fresh workspace and prove round-trip behavior and deterministic ordering; report imported:3.`,
  `Preserve all prior behavior and modify only candidate source files. Turn 5: make writes atomic through ledger.json.tmp followed by rename; recover a valid temporary ledger after the primary is removed and report recovered:3.`,
  `Preserve all prior behavior and modify only candidate source files. Turn 6: reject malformed input without mutating state; accept the exact agentbattler.ledger.v1-compatible schema with a compat event sequence 99.`,
  `Modify only candidate source files. Turn 7: perform a complete visible-contract audit and repair every regression. Do not finish until the prior behavior is preserved.`,
  `Modify only candidate source files. Turn 8: perform the final performance and contract audit, including the bounded 24-record workload. Preserve every earlier contract exactly.`,
]);
